const carData = [
  {
    id: '1',
    patente: 'AB123CD',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2021,
    type: 'compact',
    passengers: 4,
    transmission: 'automatic',
    fuel: 'gas',
    pricePerDay: 50,
    availability: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/2021_Toyota_Corolla_SE_Hatchback.jpg/480px-2021_Toyota_Corolla_SE_Hatchback.jpg'
  },
  {
    id: '2',
    patente: 'EF456GH',
    brand: 'Ford',
    model: 'Mustang',
    year: 2019,
    type: 'sport',
    passengers: 4,
    transmission: 'manual',
    fuel: 'gas',
    pricePerDay: 100,
    availability: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/2019_Ford_Mustang_GT_Blue.jpg/375px-2019_Ford_Mustang_GT_Blue.jpg'
  },
  {
    id: '3',
    patente: 'IJ789KL',
    brand: 'Honda',
    model: 'Civic',
    year: 2017,
    type: 'compact',
    passengers: 6,
    transmission: 'automatic',
    fuel: 'electric',
    pricePerDay: 10,
    availability: false,
    image: 'https://cdn.motor1.com/images/mgl/WV6rr/s4/lanzamiento-honda-civic-2017.webp'
  },
  {
    id: '4',
    patente: 'MN012OP',
    brand: 'Chevrolet',
    model: 'Camaro',
    year: 2018,
    type: 'sport',
    passengers: 4,
    transmission: 'manual',
    fuel: 'gas',
    pricePerDay: 120,
    availability: false,
    image: 'https://www.chevrolet.com.ar/content/dam/chevrolet/mercosur/argentina/espanol/index/performance/2018-camaro-conversivel/colorizer/01-images/novo-camaro-conversivel-2018-amarelo-mov-intro-01.png'
  },
  {
    id: '5',
    patente: 'QR345ST',
    brand: 'Nissan',
    model: 'GT-R',
    year: null,
    type: 'sport',
    passengers: 6,
    transmission: 'automatic',
    fuel: 'gas',
    pricePerDay: 20,
    availability: false,
    image: 'https://acnews.blob.core.windows.net/imgnews/large/NAZ_7387335f56554b7c9b9891cf2688a25f.jpg'
  },
  { 
    id: '6',
    patente: 'UV678WX',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2022,
    type: 'compact',
    passengers: 4,
    transmission: 'automatic',
    fuel: 'electric',
    pricePerDay: 50,
    availability: false,
    image: 'https://cdn.topgear.es/sites/navi.axelspringer.es/public/media/image/2022/09/tesla-model-3-2829983.jpg?tf=640x'
  },
  {
    id: '7',
    patente: 'YZ901AB',
    brand: 'Volkswagen',
    model: 'Golf',
    year: null,
    type: 'compact',
    passengers: 4,
    transmission: 'manual',
    fuel: 'electric',
    pricePerDay: 30,
    availability: false,
    image: 'https://acnews.blob.core.windows.net/imgnews/large/NAZ_51b9c4db18564c9a891527954752461c.jpg'
  },
  {
    id: '8',
    patente: 'CD234EF',
    brand: 'Toyota',
    model: 'RAV4',
    year: null,
    type: 'SUV',
    passengers: 6,
    transmission: 'automatic',
    fuel: 'hybrid',
    pricePerDay: 80,
    availability: false,
    image: 'https://acnews.blob.core.windows.net/imgnews/large/NAZ_4c3afd5296c945248b18f8194b42183f.webp'
  },
  {
    id: '9',
    patente: 'GH567IJ',
    brand: 'Hyundai',
    model: 'Tucson',
    year: 2021,
    type: 'SUV',
    passengers: 6,
    transmission: 'automatic',
    fuel: 'hybrid',
    pricePerDay: 80,
    availability: false,
    image: 'https://autotest.com.ar/wp-content/uploads/2020/09/HYUNDAI-TUCSON-2021-PORTADA-e1600133392582.jpg'
  },
  {
    id: '10',
    patente: 'KL890MN',
    brand: 'Ford',
    model: 'Explorer',
    year: null,
    type: 'SUV',
    passengers: 6,
    transmission: 'automatic',
    fuel: 'diesel',
    pricePerDay: 10,
    availability: false,
    image: 'https://acnews.blob.core.windows.net/imgnews/large/NAZ_11c6a504359c4419b6aa818f14246ada.jpg'
  },
  {
    id: '11',
    patente: 'OP123QR',
    brand: 'Jeep',
    model: 'Wrangler',
    year: null,
    type: 'SUV',
    passengers: 6,
    transmission: 'manual',
    fuel: 'gas',
    pricePerDay: 150,
    availability: false,
    image: 'https://www.infobae.com/new-resizer/aq1HCFZknqnBDGg4JoI_yJkqhpE=/768x432/filters:format(webp):quality(85)/arc-anglerfish-arc2-prod-infobae.s3.amazonaws.com/public/654SU46FCVC2DGP6X6GNZYK6NY.jpg'
  },
  {
    id: '12',
    patente: 'ST456UV',
    brand: 'Mazda',
    model: 'CX-5',
    year: null,
    type: 'compact',
    passengers: 4,
    transmission: 'automatic',
    fuel: 'gas',
    pricePerDay: 220,
    availability: false,
    image: 'https://cdn.motor1.com/images/mgl/1mjRW/s4/2022-mazda-cx-5.webp'
  },
  {
    id: '13',
    patente: 'WX789YZ',
    brand: 'Kia',
    model: 'Sportage',
    year: null,
    type: 'compact',
    passengers: 4,
    transmission: 'automatic',
    fuel: 'electric',
    pricePerDay: 74,
    availability: false,
    image: 'https://acnews.blob.core.windows.net/imgnews/large/NAZ_fbede6fa89524547b78c1249648305f3.jpg'
  },
  {
    id: '14',
    patente: 'AB123CD',
    brand: 'Subaru',
    model: 'Outback',
    year: null,
    type: 'compact',
    passengers: 4,
    transmission: 'automatic',
    fuel: 'hybrid',
    pricePerDay: 14,
    availability: false,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/2020_Subaru_Outback_AWD%2C_front.jpg/800px-2020_Subaru_Outback_AWD%2C_front.jpg'
  },
  {
    id: '15',
    patente: 'CD456EF',
    brand: 'Tesla',
    model: 'Model S',
    year: null,
    type: 'sedan',
    passengers: 4,
    transmission: 'automatic',
    fuel: 'electric',
    pricePerDay: 4,
    availability: false,
    image: 'https://cdn.computerhoy.com/sites/navi.axelspringer.es/public/media/image/2017/09/261183-ya-no-puedes-comprar-tesla-model-s.jpg?tf=640x'
  }
];

export default carData;
